name: pumpmonitoring
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  

  flutter_localizations: 
    sdk: flutter

  # library : pub.dev

  
  cupertino_icons: ^1.0.2

  #local storage
  shared_preferences: ^2.0.15

  #firebase configuration
  firebase_core: ^1.10.0
  firebase_messaging: ^11.1.0
  cloud_firestore: ^3.1.17
  firebase_auth: ^3.3.20
  firebase_database: ^7.1.1
 

  #local notification
  flutter_local_notifications: ^8.2.0

  #dashboard utils
  shimmer: ^2.0.0
  fl_chart: ^0.51.0
  intl: ^0.17.0
  localization: ^2.1.0
  buttons_tabbar: ^1.3.5
  flutter_animated_button: ^2.0.0

  #integration network
  provider: ^6.0.2
  http: ^0.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.3
  
flutter_icons:
  android: true
  image_path: "assets/images/logo.png"

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

